# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
